import type { ClientTheme } from "../types"

export const croixRougeFrancaise: ClientTheme = {
    id: "croix-rouge-francaise",
    name: "Croix-Rouge francaise",
    shortName: "CRF",

    logo: {
        svgPath: "M9 2h6v7h7v6h-7v7H9v-7H2V9h7V2z",
        viewBox: "0 0 24 24",
        useBrandColor: true,
    },

    brand: {
        primary: "#ff010b",
        primaryLight: "#ffcbbe",
        secondary: "#1dbfee",
        secondaryLight: "#c2d9ff",
        accent1: "#cebfff",
        accent1Light: "#ebe5ff",
        accent2: "#13d3aa",
        accent2Light: "#cbf1e4",
    },

    light: {
        // Light theme - blanc et rouge dominant
        background: "#fefefe",
        foreground: "#000000",
        card: "#ffffff",
        cardForeground: "#000000",
        popover: "#ffffff",
        popoverForeground: "#000000",
        primary: "#ff010b",
        primaryForeground: "#fefefe",
        secondary: "#ffcbbe",
        secondaryForeground: "#000000",
        muted: "#f5f5f5",
        mutedForeground: "#525252",
        accent: "#ffcbbe",
        accentForeground: "#000000",
        destructive: "#ff010b",
        border: "#e5e5e5",
        input: "#e5e5e5",
        ring: "#ff010b",
        // Chart colors
        chart1: "#ff010b",
        chart2: "#13d3aa",
        chart3: "#1dbfee",
        chart4: "#cebfff",
        chart5: "#ffcbbe",
        // Sidebar
        sidebar: "#fefefe",
        sidebarForeground: "#000000",
        sidebarPrimary: "#ff010b",
        sidebarPrimaryForeground: "#fefefe",
        sidebarAccent: "#ffcbbe",
        sidebarAccentForeground: "#000000",
        sidebarBorder: "#e5e5e5",
        sidebarRing: "#ff010b",
        // Status
        warning: "#cebfff",
        warningForeground: "#000000",
        success: "#13d3aa",
        successForeground: "#000000",
        critical: "#ff010b",
        criticalForeground: "#fefefe",
    },

    dark: {
        // Dark theme - noir et bleu dominant
        background: "#000000",
        foreground: "#fefefe",
        card: "#0a0a0a",
        cardForeground: "#fefefe",
        popover: "#0a0a0a",
        popoverForeground: "#fefefe",
        primary: "#1dbfee",
        primaryForeground: "#000000",
        secondary: "#c2d9ff",
        secondaryForeground: "#000000",
        muted: "#1a1a1a",
        mutedForeground: "#a3a3a3",
        accent: "#c2d9ff",
        accentForeground: "#000000",
        destructive: "#ff010b",
        border: "#262626",
        input: "#262626",
        ring: "#1dbfee",
        // Chart colors
        chart1: "#1dbfee",
        chart2: "#13d3aa",
        chart3: "#ff010b",
        chart4: "#cebfff",
        chart5: "#c2d9ff",
        // Sidebar
        sidebar: "#000000",
        sidebarForeground: "#fefefe",
        sidebarPrimary: "#1dbfee",
        sidebarPrimaryForeground: "#000000",
        sidebarAccent: "#0d3a4a",
        sidebarAccentForeground: "#fefefe",
        sidebarBorder: "#262626",
        sidebarRing: "#1dbfee",
        // Status
        warning: "#cebfff",
        warningForeground: "#000000",
        success: "#13d3aa",
        successForeground: "#000000",
        critical: "#ff010b",
        criticalForeground: "#fefefe",
    },
}
